AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  IgnoredMethods: ['it', 'describe', 'context', 'let', 'specify']
  Exclude:
    - acts_as_hashable.gemspec

Style/RescueModifier:
  Enabled: false
